cumulusci.yml
We are updating K12's Cumulus.yml file to ensure that each tasks and flows have descriptions. 
We have updated qa_org flow to ensure that it mimics dev_org flow so that QE team can use this flow when spinning up a testing org. 
We have updated dev_org and dev_org_namespaced flows to include deploy_k12_kit_settings task so that it defaults the org's Account model to Household. 
We have updated qa_org, dev_org, and dev_org_namespaced flow where snapshot_changes task is added as the last step for each flow.
=> W-037412: [K12]: Add descriptions and update K12 cci flows

cumulusci.yml, unpackaged/config/installer/package.xml, unpackaged/config/installer/profiles/Admin.profile
- The K-12 Architecture Kit application tile is now visible from the App Launcher for users with the System Administrator profile when the K-12 Architecture Kit is installed with the installer link.
- Fixes: #142 
- A new cci task has been created and added the the install plan in cci. However you cannot run plans so the steps to test in a local org are:
-- cci task run update_dependencies
-- cci task run deploy_pre -o unmanaged False
-- cci task run install_managed 
-- cci task run deploy_post -o unmanaged False
-- cci task run deploy_k12_app
After running these tasks against a fresh scratch org, you should see the K12 app has been added to the launcher.
=> Add K12 App tile to Launcher when installing from link

cumulusci.yml
This PR adds `deploy_trial_config` and `enable_course_connections` tasks to `config_regression`.
----
``` console
$ cci flow run regression_org --org release
```
=> Extend regression flow with trial and course connections

tasks/salesforce.py
Recent change in CCI (SFDO-Tooling/CumulusCI#1456) meant our custom task needs
to be updated to reference the correct variable name.
----
``` shell
cci task run update_admin_profile --org dev
```
=> Fix UpdateAdminProfile custom task override

cumulusci.yml, documentation/automation.md
This PR adds some detail to the existing docs to address the TSO process, as well as list workflows and their corresponding CCI tasks/flows. In addition, task/flow group names have been updated to add the `K12` prefix to make them easier to spot.
----
=> [K12] Expand automation documentation

src/objects/Grade_Enrollment__c.object, unpackaged/config/trial/objects/___NAMESPACE___Grade_Enrollment__c.object
We have updated the Grade Enrollment Exist Reason picklist value from "No Show" to "No-Show."
New customers will automatically get this updated value; we recommend that existing customers update the picklist label manually. 
Closes #173
Trial org:
- Run cci org scratch trial 
- Run cci flow run trial_org 
- Ensure that "No-Show" is showing as the picklist value for Exist Reason on Grade Enrollment. 
Non trial org:
- Run cci org scratch dev
- Run cci flow dev_org 
- Ensure that "No-Show" is showing as the picklist value for Exist Reason on Grade Enrollment.
=> K12 Update the Exit Reason picklist value to "No-Show" on Grade Enrollment

tasks/legacy_update_profile.py, tasks/salesforce.py
This PR adds a local copy of the UpdateAdminProfile class as shipped in CumulusCI 3.8.0. This ensures that K12's local subclass of UpdateAdminProfile can continue to function while CumulusCI's implementation changes in a near-future release.
=> Add local copy of UpdateAdminProfile to support subclass

cumulusci.yml, tasks/legacy_update_profile.py
The default xml file included in cumulusci package has changed. This PR adds the content of the old default package XML as a constant.
This is a temporary fix until we can refactor salesforce.py.
----
=> [K12] Use default package_xml in legacy class

src/layouts/hed__Behavior_Response__c-K12 Kit Behavior Response Layout.layout, src/objectTranslations/hed__Behavior_Response__c-ca.objectTranslation, src/objectTranslations/hed__Behavior_Response__c-en_US.objectTranslation, src/objectTranslations/hed__Behavior_Response__c-es.objectTranslation, src/objectTranslations/hed__Behavior_Response__c-fr.objectTranslation, src/objects/hed__Behavior_Response__c.object, src/package.xml, unpackaged/config/trial/objects/hed__Behavior_Response__c.object
You can now track the number of days a student misses school in response to a Behavior Incident. For new customers, the "School Days Missed" field is automatically added to the Behavior Response page layout. Existing customers can add it to page layouts manually. See [Display a New Custom Object After a Product Release](https://powerofus.force.com/s/article/EDA-Display-Cust-Obj-Post-Rel).
Closes #184 
School_Days_Missed__c
The field 'School Days Missed' should be visible on the page layout and should be defined as per the SPEC https://salesforce.quip.com/wtXAAIfa4mmZ#DJBACAxyxmZ.
The changes for TSO should be tested after the merge to Master.
=> [K-12] Tracking School Days Missed on Behavior Response

cumulusci.yml, sfdx-project.json, src/classes/CON_CurrentGradeLevel_TDTM.cls-meta.xml, src/classes/CON_CurrentGradeLevel_TEST.cls-meta.xml, src/classes/GRER_SyncGradeLevel_TDTM.cls-meta.xml, src/classes/GRER_SyncGradeLevel_TEST.cls-meta.xml, src/classes/STG_InstallScript.cls-meta.xml, src/classes/STG_InstallScript_TEST.cls-meta.xml, src/classes/TDTM_DefaultConfig.cls-meta.xml, src/classes/TDTM_ProcessControl.cls-meta.xml, src/classes/UTIL_Namespace.cls-meta.xml, src/classes/UTIL_Namespace_TEST.cls-meta.xml, src/package.xml, src/tabs/Grade_Enrollment__c.tab, src/triggers/TDTM_GradeEnrollment.trigger-meta.xml, tasks/add_picklist_values.py, tasks/legacy_update_profile.py, tasks/test_add_picklist_values.py, unpackaged/config/installer/package.xml, unpackaged/config/trial/package.xml, unpackaged/post/config/package.xml, unpackaged/post/config/settings/Language.settings, unpackaged/post/config/settings/OrgPreference.settings, unpackaged/pre/recordtypes/package.xml
We've updated K-12 Architecture Kit to use API Version v48.0 to align with the most current version of the API. Additionally, we have removed references to the deprecated mobileReady attribute from the Grade Enrollment tab. We've replaced the Translation preference in the deprecated OrgPreference.settings component with the enableTranslationWorkbench field in the Language.settings component. You'll see no change to your org as a result of this update.
=> [K12] Update the API version number K12 wide

cumulusci.yml, tasks/add_picklist_values.py
We've added new picklist values to the existing "Type" field on Behavior Response. 
- Detention
- Expulsion with Services
- In-School Suspension
- Out-of-School Suspension
- Removal from Classroom
We've also added these picklist values to the existing "Location" field on Case for Behavior Response. 
- Administrative offices area
- Athletic field or playground
- Auditorium
- Bus stop
- Cafeteria area
- Classroom
- Computer lab
- Hallway or stairs
-  Library/media center
- Locker room or gym areas
- Online
- Parking lot
- Restroom
- School bus
- Stadium
- Unknown
- Walking to or from school
For new installations, the new picklist values are automatically included. If you installed an earlier EDA release, manually add the new picklist values to the "Type" field on Behavior Response and to …
=> [K12] Picklist Updates to Case(Behavior Involvement) and Behavior Response Objects

tasks/picklists.py
Add a localized task to allow the use of the MetadataETL add picklist task pre-cumulusci release.
=> [K12] Localize metadataETL add picklist value task 

unpackaged/config/trial/layouts/hed__Behavior_Response__c-K12 Kit Behavior Response Layout.layout
Updated the field reference in the BEH page layout in trial folder from School_Days_Missed__c to %%%NAMESPACE%%%School_Days_Missed__c. 
* Merge feature/positiveBehavior into feature/positiveBehavior__kdyBR [[PR226](https://github.com/SalesforceFoundation/k12-architecture-kit/pull/226)]
=> [K12] Build Issue with "School Days Missed" Field on BEH Page Layout

unpackaged/config/trial/objects/hed__Course_Offering__c.object, unpackaged/config/trial/objects/hed__Course__c.object, unpackaged/post/config/objects/hed__Course_Offering__c.object, unpackaged/post/config/objects/hed__Course__c.object
We've updated descriptions on fields to match with EDA's descriptions. With this change we corrected casing of "Course" in the object description for Course Offering and added description to the field 'hed__Account__c' on 'Course' object.
=> [K12] Update labels/descriptions to match EDA's latest updates

src/classes/EDUHIS_DataInteg_TDTM.cls, src/classes/EDUHIS_DataInteg_TEST.cls, src/classes/GRER_DataInteg_TDTM.cls, src/classes/GRER_DataInteg_TEST.cls, src/classes/TDTM_DefaultConfig.cls
*Fixed tests for the Education History unit tests.
*Added non-significant change to return a unique list of education histories that are in an error state rather than the same education history for every grade enrollment mismatch
=> Unit Test Fixes for Education History Warning Message

cumulusci.yml
CumulusCI v3.20.0 renamed `github_parent_to_child` to `github_automerge_feature`. Apologies I didn't catch this earlier.
Currently causing builds to fail like this:
https://sfdo-metaci.herokuapp.com/builds/322654/flows
=> Update to current task name

cumulusci.yml
Added a new task to K12 cumulus.yml file to reference an EDA task that adds new picklist value for hed__Citizenship_Status__c on Contact. 
Close #295
=> [K12] Add task to K12 yml to support New Picklists Value for Citizenship Status on Contact

cumulusci.yml, scripts/configure_k12_kit.cls
Run the qa_org_2gp flow. This made qa_org intelligently work with unmanaged vs managed.
=> QA Org 2gp Does Not Use Managed Configuration

cumulusci.yml
1. Run the qa_org_2gp against a prerelease org shape.
1. Confirm that the K-12 Architecture Kit app is in the app launcher for System Administrator.
=> Installer config added to regression config

cumulusci.yml, metadeploy/labels_en.json
This PR adds preflight checks for My Domain and Chatter to the K-12 installer.
=> Add preflight checks
