README.md

This PR adds a direct link to the K-12 Architecture Kit installer.
----

Add installer link to README

---

src/layouts/Account-K12 Kit Household Layout.layout
src/layouts/Case-K12 Kit Incident Layout.layout
src/layouts/Contact-K12 Kit Faculty Staff Layout.layout
src/layouts/Contact-K12 Kit Guardian Layout.layout
src/layouts/Contact-K12 Kit Student Layout.layout
src/layouts/Grade_Enrollment__c-K12 Kit Grade Enrollment Layout.layout
src/layouts/hed__Attendance_Event__c-K12 Kit Attendance Event Layout.layout
src/layouts/hed__Attribute__c-K12 Kit Credential Layout.layout
src/layouts/hed__Attribute__c-K12 Kit Student Characteristic Layout.layout
src/layouts/hed__Behavior_Involvement__c-K12 Kit Behavior Involvement Layout.layout
src/layouts/hed__Behavior_Response__c-K12 Kit Behavior Response Layout.layout
src/layouts/hed__Course_Enrollment__c-K12 Kit Teacher Course Connection Layout.layout
src/layouts/hed__Relationship__c-K12 Kit Relationship Layout.layout
src/layouts/hed__Term_Grade__c-K12 Kit Term Grade Layout.layout
unpackaged/config/trial/profiles/Admin.profile
unpackaged/post/config/flexipages/K12_Account_Record_Page.flexipage
unpackaged/post/config/flexipages/K12_Address_Record_Page.flexipage
unpackaged/post/config/flexipages/K12_Contact_Record_Page.flexipage
unpackaged/post/config/flexipages/K12_Program_Enrollment_Record_Page.flexipage
unpackaged/post/config/flexipages/K12_Term_Grade_Record_Page.flexipage

We've updated K-12 page layouts to be more consistent.

W-037002 - [K12 Kit] - Ensure Quick Actions and Activities Feed For Each Object Match Specifications

---

cumulusci.yml

`cci flow info regression_org`

Fixing regression configuration in cumulus.yml

---

orgs/beta_prerelease.json

Add Beta Prerelease org config

---

unpackaged/post/config/objects/___NAMESPACE___Grade_Enrollment__c.object
unpackaged/post/config/objects/hed__Attribute__c.object
unpackaged/post/config/objects/hed__Relationship__c.object
unpackaged/post/config/package.xml

We have added new list views for Attribute (Credentials and Student Characteristics), Grade Enrollments, and Relationship objects. 
Closes #141 
See https://salesforce.quip.com/ftpeAGVNqTTP

[K12 Kit] Add list views and columns for K12 objects (see description)

---

unpackaged/config/trial/objects/___NAMESPACE___Grade_Enrollment__c.object
unpackaged/config/trial/objects/hed__Attribute__c.object
unpackaged/config/trial/objects/hed__Relationship__c.object
unpackaged/config/trial/package.xml

[K12] Create a New Object Folder in the Trial Folder in Unpackaged Folder

---

cumulusci.yml

Required for `update_admin_profile` to run.
----

Set minimum_cumulusci_version to 3.5.0

---

orgs/trial.json

Updating k12-architecture-kit trialforce template id

---

cumulusci.yml

[K12 Kit]: Create EDA Feature Tests for K12

---

orgs/trial.json

[K-12 kit] Updating template trial org id to reflect the 1.6 k12 release

---

unpackaged/config/trial/objects/Contact.object

We've updated our internal tooling to include certain EDA picklist values in the K-12 Trial Source Org flow.
- Create trial org and run trial_org flow

[K12]  Add New Picklist Values To Existing Contact Fields To Match EDA's TSO

---

cumulusci.yml

[EDA] Updating add application picklist values to add to upgraded_org, dev_org_namespaced, and dev_org flows.

---

cumulusci.yml

[K12-kit] Update EDA url dependency

---

orgs/trial.json

[K-12 kit] 1.7 template id

---

cumulusci.yml

[K12-kit] Updating with unpinned github tag

---

orgs/trial.json

[K12-kit] Updating for K12-kit 1.8 release trialforce template id

---

unpackaged/config/trial/objects/hed__Behavior_Response__c.object

removed TSO updates fro School_Days_Missed__c field

---

orgs/trial.json

[K12] Update trialforce template id

---

cumulusci.yml
documentation/automation.md

[k12-kit] Create EDA net new org flow

---

orgs/trial.json

[K-12] Update K12 1.10 trialforce template id

---

orgs/trial.json

[K12-kit] Update trialforce template id k12  1.11

---

orgs/trial.json

[K12-kit] Update k12 1.12 trialforce template id

---

orgs/trial.json

[K12] Update K12 1..13 trialforce template id

---

orgs/trial.json

[K12] Update K12 1.14 trialforce template id

---

cumulusci.yml

This PR serves to automate the proper reordering of values, which are already present in the TSO. These values have to be manually reordered due to the limitations of the current code. This PR serves to automate the reordering, but will be deprecated by https://github.com/SalesforceFoundation/k12-architecture-kit/pull/220

[K12] Push application type picklist temporary fix

---

cumulusci.yml

Added picklist task to installer flow

---

orgs/trial.json

[K12] Update K-12 1.16 trialforce template id

---

orgs/trial.json

[K12] Update trialforce template id for version 1.17

---

unpackaged/config/trial/layouts/Account-___NAMESPACE___K12 Kit Educational Institution Layout.layout
unpackaged/config/trial/package.xml

Fix package.xml and layout file  to deploy 2 additional layouts and fields.

[K12] Pushing fix to allow TSO automation for K12 1.18

---

unpackaged/config/trial/layouts/Account-___NAMESPACE___K12 Kit Educational Institution Layout.layout
unpackaged/config/trial/package.xml

Feature/k12 1.18

---

orgs/trial.json

[K12] Update K12 1.18 trialforce template ID

---

orgs/trial.json

Does exactly what the pull request title says!

[K12] Update trialforce template ID for K12 1.20

---

orgs/trial.json

[K12] Updating trialforce id to represent EDA 1.108 update

---

.github/PULL_REQUEST_TEMPLATE.md

[K12] Updated Pull Request Template

---

cumulusci.yml

[K12] Create Trialforce Template ID section through automation

---

orgs/trial.json

[K12] Updating trialforce template for EDA 1.110 update

---

cumulusci.yml
orgs/regression.json
scripts/configure_k12_kit.cls

Fix 2gp install scripts

---

cumulusci.yml
orgs/regression.json
scripts/configure_k12_kit.cls

All changes reflect CCI and tooling related changes. There are no functional changes to K12 kit in this release.

Tooling Updates to K12 Kit

---

README.md
package.json
yarn.lock

[K12] prettier precommit check

---

cumulusci.yml

Add EDA Health Check step

---

cumulusci.yml
unpackaged/post/config/applications/K12Kit.app

Updated K12 kit app to use Education Cloud Settings

---

cumulusci.yml
metadeploy/labels_en.json

Update installer options for EDA

---

orgs/trial.json

Update TSO id

---

README.md
metadeploy/labels_en.json

This pull request updates the documentation/user group references.
- [W-10540445](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000lFPizYAG/view)

[W-10540445] Update EDA & K12 Power of Us hub document links

---

README.md
metadeploy/labels_en.json

* Updated the installer text to reflect the Power of Use hub changes.

Feature 238 - K12 Kit Installer Text Updates - Power of Us Hub change

---

yarn.lock

ugprading pacakges in yarn

---

.github/ISSUE_TEMPLATE.md
README.md
metadeploy/labels_en.json

- [[W-11670135]](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000015HEWtYAO/view)

[w-11670135] Removed power of us url's

---

.github/ISSUE_TEMPLATE.md
README.md
cumulusci.yml
metadeploy/labels_en.json
robot/K12/doc/Keywords.html
robot/K12/resources/BaseObjects.py
robot/K12/resources/K12.py
robot/K12/resources/K12.robot
robot/K12/resources/locators_54.py
robot/K12/tests/browsers/Setup/setupTests.robot

* Feature/242  mrrigney/automate test scenarios [[PR347](https://github.com/SalesforceFoundation/k12-architecture-kit/pull/347)]

242 Release PR

---

cumulusci.yml

Remove preproduction override
